# Site settings
title            : "Lindsay Popowski"
description      : "PhD candidate in Computer Science at Stanford University"
url              : "https://lipopowski.github.io"
baseurl          : ""
email            : "popowski@stanford.edu"

# Build settings
markdown         : kramdown
permalink        : /:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - .gitignore

# Author profile (used in layout header/footer)
author:
  name           : "Lindsay Popowski"
  googlescholar  : "https://scholar.google.com/citations?user=Ef6K7mQAAAAJ&hl=en"
  github         : "lipopowski"
  twitter        : "lindsaypopowski"
  cv             : "/files/cv.pdf"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications/"
  - title: "CV"
    url: "/files/cv.pdf"
